# Generated by Django 2.1.7 on 2019-12-26 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provincejudiciary',
            old_name='related_court',
            new_name='court',
        ),
    ]
