# Generated by Django 2.1.7 on 2019-12-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0003_provinceexecutive'),
    ]

    operations = [
        migrations.AddField(
            model_name='provincejudiciary',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provincejudiciary',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
