# Generated by Django 2.1.7 on 2019-12-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0005_auto_20191227_1227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jptmodel',
        ),
    ]
