# Generated by Django 2.1.7 on 2020-02-03 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0006_delete_jptmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provinceexecutive',
            old_name='related_ministry',
            new_name='provincial_ministries',
        ),
    ]
