# Generated by Django 2.1.7 on 2020-02-03 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0007_auto_20200203_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provinceexecutive',
            old_name='provincial_ministries',
            new_name='related_ministry',
        ),
    ]
