# Generated by Django 2.1.7 on 2020-02-03 08:42

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0003_provincialparliamentoffice'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('provinces', '0008_auto_20200203_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvincialParliament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('related_file', models.FileField(blank=True, upload_to='files/')),
                ('is_private', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.Category')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pro_par_last_modified_by', to=settings.AUTH_USER_MODEL)),
                ('parliament_office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='offices.ProvincialParliamentOffice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
