# Generated by Django 2.1.7 on 2020-02-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0011_auto_20200203_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvincesName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_Province', models.CharField(max_length=70)),
            ],
        ),
    ]
