# Generated by Django 2.1.7 on 2020-02-04 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0013_auto_20200204_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='provincesname',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='provincesname',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
