# Generated by Django 2.1.7 on 2020-02-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0014_auto_20200204_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provincesname',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='provincesname',
            name='modified_date',
        ),
    ]
