# Generated by Django 2.1.7 on 2020-02-09 06:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0015_auto_20200204_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provinceexecutive',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='contenido'),
        ),
        migrations.AlterField(
            model_name='provincejudiciary',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='contenido'),
        ),
        migrations.AlterField(
            model_name='provincialparliament',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='contenido'),
        ),
    ]
