# Generated by Django 2.1.7 on 2020-02-09 06:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0017_auto_20200209_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='provinceexecutive',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provincejudiciary',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provincialparliament',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provinceexecutive',
            name='description',
            field=models.CharField(default=False, max_length=130),
        ),
        migrations.AlterField(
            model_name='provincejudiciary',
            name='description',
            field=models.CharField(default=False, max_length=130),
        ),
        migrations.AlterField(
            model_name='provincialparliament',
            name='description',
            field=models.CharField(default=False, max_length=130),
        ),
    ]
