# Generated by Django 2.1.7 on 2020-02-11 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0022_auto_20200209_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincejudiciary',
            name='court',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='offices.ProvinceJudiciaryOffice'),
        ),
    ]
