# Generated by Django 2.1.7 on 2020-02-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0031_auto_20200211_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='provinceexecutive',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='provincejudiciary',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='provincialparliament',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
