# Generated by Django 2.1.7 on 2020-02-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0032_auto_20200211_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provinceexecutive',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='provincejudiciary',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='provincialparliament',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
