# Generated by Django 2.1.7 on 2019-12-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Federal', '0003_auto_20191211_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='executive',
            old_name='related_files',
            new_name='related_file',
        ),
        migrations.AddField(
            model_name='executive',
            name='related_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
