# Generated by Django 2.1.7 on 2019-12-12 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Federal', '0005_remove_executive_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='author',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
