# Generated by Django 2.1.7 on 2019-12-12 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Federal', '0014_executive_last_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='last_modified_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
