# Generated by Django 2.1.7 on 2019-12-12 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Federal', '0015_executive_last_modified_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executive',
            name='last_modified_on',
        ),
    ]
