# Generated by Django 2.1.7 on 2019-12-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Federal', '0016_remove_executive_last_modified_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
