# Generated by Django 2.1.7 on 2019-12-12 06:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Federal', '0017_executive_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
