# Generated by Django 2.1.7 on 2019-12-12 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Federal', '0019_auto_20191212_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executive',
            name='related_photo',
        ),
    ]
