# Generated by Django 2.1.7 on 2019-12-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Federal', '0023_auto_20191216_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='judiciary',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legislative',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
