# Generated by Django 2.1.7 on 2019-12-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Federal', '0025_auto_20191217_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='judiciary',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='legislative',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
