# Generated by Django 2.1.7 on 2019-12-17 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Federal', '0029_auto_20191217_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='author',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='judiciary',
            name='author',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='legislative',
            name='author',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
