# Generated by Django 2.1.7 on 2019-12-20 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Federal', '0040_auto_20191220_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judiciary',
            name='related_court',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='offices.JudiciaryOffice'),
        ),
    ]
