# Generated by Django 2.1.7 on 2019-12-25 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Federal', '0042_executive_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executive',
            name='is_deleted',
        ),
    ]
