# Generated by Django 2.1.7 on 2019-12-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Federal', '0043_remove_executive_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
