# Generated by Django 2.1.7 on 2019-12-25 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Federal', '0044_executive_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executive',
            name='deleted',
        ),
    ]
