# Generated by Django 2.1.7 on 2019-12-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Federal', '0045_remove_executive_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='judiciary',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legislative',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
