# Generated by Django 2.1.7 on 2020-02-09 06:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Federal', '0047_auto_20191225_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='contenido'),
        ),
        migrations.AlterField(
            model_name='judiciary',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='contenido'),
        ),
        migrations.AlterField(
            model_name='legislative',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='contenido'),
        ),
    ]
