# Generated by Django 2.1.7 on 2020-02-09 06:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Federal', '0049_auto_20200209_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='judiciary',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legislative',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='executive',
            name='description',
            field=models.CharField(default=False, max_length=130),
        ),
        migrations.AlterField(
            model_name='judiciary',
            name='description',
            field=models.CharField(default=False, max_length=130),
        ),
        migrations.AlterField(
            model_name='legislative',
            name='description',
            field=models.CharField(default=False, max_length=130),
        ),
    ]
