# Generated by Django 2.1.7 on 2020-02-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Federal', '0059_auto_20200211_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='judiciary',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='legislative',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
