# Generated by Django 2.1.7 on 2020-02-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Federal', '0060_auto_20200211_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='judiciary',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='legislative',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
