# Generated by Django 2.1.7 on 2020-02-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Federal', '0062_auto_20200211_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='judiciary',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='legislative',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
