# Generated by Django 2.1.7 on 2020-02-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trymodel',
            name='title',
            field=models.CharField(default=True, max_length=80),
        ),
    ]
