# Generated by Django 2.1.7 on 2020-02-04 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softbase', '0002_trymodel_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TryModel',
        ),
    ]
